apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: graphql
build:
  artifacts:
  - image: bank/bank-on-me
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
portForward:
  - resourceType: deployment
    resourceName: bank-on-me
    namespace: bank
    port: 8080
    localPort: 8080