spring:
  application:
    name: learn-graphql-java

#voyager:
#  enabled: false

graphql:
  servlet:
    max-query-depth: 100
    exception-handlers-enabled: true
  playground:
    enabled: true
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Sample bank account query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_vars.json